version: '3'
services:
  web:
    build: ../4-flask-redis
    image: future-flask-redis:latest
    ports:
      - 5000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: web-python-flasks
  redis:
    image: redis:alpine
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: redis
  nginx:
    image: nginx:latest
    ports:
        - 8080:80
    volumes:
        - "../5-loadbalance/nginx/nginx.conf:/etc/nginx/nginx.conf"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx-loadbalance
