version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: future-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
        - jenkins_home:/var/jenkins_home

## Show Jenkins initial PASSWORD:
##    docker exec future-jenkins cat /var/jenkins_home/secrets/initialAdminPassword
