version: '3'
services:
  web:
    #build: .
    image: future-flask-redis:latest
    ports:
      - 5000
  redis:
    image: redis:alpine
  haproxy:
    image: dockercloud/haproxy
    ports:
      - 8080:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
